import axios, {
  AxiosError,
  AxiosResponse,
  InternalAxiosRequestConfig,
} from "axios";
import { parseCookies } from "nookies";

const cookies = parseCookies();

const API = axios.create({
  baseURL: "?",
  timeout: 8000,
  API_KEY: "sk_live_axios451OzK7cHg7F7a1234567890abcdefghijklmno",
  ACCESS_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJiNTY0ZTliNi0wNmM4LTQ1M2YtYWY4YS0zZDY5NGY5ZTQwMDYiLCJlbWFpbCI6ImRldmVsb3BtZW50LnRlYW1AcGVha2V5ZS5jb20iLCJyb2xlIjoiQWRtaW4iLCJSb2xlSWQiOiI5NWYyNjFlOC0xNzZmLTQ0YTktOGUyNS1mZGM2OTM3NDJjODUiLCJPcmdhbml6YXRpb25OYW1lIjoiUGVha2V5ZSIsIk9yZ2FuaXphdGlvbklkIjoiZTQyOWVhMjQtNDU5Ny00YWQ1LTgyMTktOGVjOTQ3YzgxMzhlIiwiUGVybWlzc2lvbiI6WyJFZGl0T3JnYW5pemF0aW9ucyIsIkNyZWF0ZU1pc2NvbmZpZ3VyYXRpb25zIiwiVmlld1Z1bG5lcmFiaWxpdGllcyIsIlZpZXdBc3NldERldGFpbHMiLCJWaWV3SXNzdWVUeXBlcyIsIkVkaXRJc3N1ZUNvbW1lbnRzIiwiVmlld1VzZXJzIiwiRWRpdE1pc2NvbmZpZ3VyYXRpb25zIiwiQ3JlYXRlVnVsbmVyYWJpbGl0aWVzIiwiQXNzaWduQXNzZXNzbWVudHMiLCJDcmVhdGVBc3NldERldGFpbHMiLCJDcmVhdGVVc2VycyIsIkRlbGV0ZU1pc2NvbmZpZ3VyYXRpb25zIiwiRWRpdFZ1bG5lcmFiaWxpdGllcyIsIkVkaXRBc3NldERldGFpbHMiLCJFZGl0VXNlcnMiLCJEZWxldGVWdWxuZXJhYmlsaXRpZXMiLCJWaWV3VXNlcnNBbmRUZWFtcyIsIkRlbGV0ZUFzc2V0RGV0YWlscyIsIkRlbGV0ZVJlcG9ydFRlbXBsYXRlcyIsIkRlbGV0ZVVzZXJzIiwiVmlld1RlYW1Bc3NldHMiLCJWaWV3UmVwb3J0VGVtcGxhdGVzIiwiVmlld0Fzc2V0cyIsIkRlbGV0ZUlzc3VlUHJpb3JpdGllcyIsIlZpZXdBc3Nlc3NtZW50cyIsIlNlbmRNYWlsSW52aXRlVXNlcnMiLCJDcmVhdGVUZWFtQXNzZXRzIiwiVmlld1Z1bG5lcmFiaWxpdHlTdGF0dXNSZXF1ZXN0cyIsIkNyZWF0ZUFzc2V0cyIsIlZpZXdJc3N1ZVN0YXR1c2VzIiwiRWRpdEFzc2V0cyIsIlZpZXdTY2FucyIsIkRlbGV0ZVRlYW1Bc3NldHMiLCJFZGl0VnVsbmVyYWJpbGl0eVN0YXR1c1JlcXVlc3RzIiwiQXNzaWduQ291cnNlcyIsIkRlbGV0ZUFzc2V0cyIsIkNyZWF0ZVNjYW5zIiwiQ3JlYXRlSXNzdWVzIiwiVmlld0Fzc2V0R3JvdXBzIiwiRGVsZXRlU2NhbnMiLCJWaWV3SXNzdWVzIiwiRWRpdElzc3VlUHJpb3JpdGllcyIsIlZpZXdUZWFtcyIsIkVkaXRJc3N1ZXMiLCJDcmVhdGVBc3NldEdyb3VwcyIsIkRlbGV0ZUlzc3VlQWN0aXZpdGllcyIsIkRlbGV0ZUlzc3VlVHlwZXMiLCJFZGl0SXNzdWVQcm9qZWN0cyIsIlZpZXdMb2dzIiwiQ3JlYXRlVGVhbXMiLCJFZGl0QXNzZXRHcm91cHMiLCJWaWV3SXNzdWVBY3Rpdml0aWVzIiwiQ3JlYXRlSXNzdWVTdGF0dXNlcyIsIlZpZXdJc3N1ZVByb2plY3RzIiwiRGVsZXRlSXNzdWVDb21tZW50cyIsIkRlbGV0ZUlzc3VlUHJvamVjdHMiLCJEZWxldGVBc3NldEdyb3VwcyIsIlZpZXdXb3JrZmxvd3MiLCJFZGl0VGVhbXMiLCJWaWV3SW50ZWdyYXRpb25zIiwiQ3JlYXRlV29ya2Zsb3dzIiwiRGVsZXRlVGVhbXMiLCJDcmVhdGVJc3N1ZUFjdGl2aXRpZXMiLCJFZGl0SXNzdWVTdGF0dXNlcyIsIkVkaXRJc3N1ZUFjdGl2aXRpZXMiLCJDcmVhdGVJc3N1ZVByaW9yaXRpZXMiLCJFZGl0SXNzdWVUeXBlcyIsIkNyZWF0ZUludGVncmF0aW9ucyIsIkVkaXRXb3JrZmxvd3MiLCJWaWV3VXNlclRlYW1zIiwiVmlld0NvdXJzZXMiLCJDcmVhdGVJc3N1ZVR5cGVzIiwiRWRpdEludGVncmF0aW9ucyIsIkNyZWF0ZVVzZXJUZWFtcyIsIkRlbGV0ZVdvcmtmbG93cyIsIkRlbGV0ZUlzc3VlU3RhdHVzZXMiLCJDcmVhdGVJc3N1ZVByb2plY3RzIiwiVmlld0lzc3VlUHJpb3JpdGllcyIsIkVkaXRSZXBvcnRUZW1wbGF0ZXMiLCJEZWxldGVVc2VyVGVhbXMiLCJWaWV3TWlzY29uZmlndXJhdGlvbnMiLCJWaWV3TWVudHMiLCJDcmVhdGVSZXBvcnRUZW1wbGF0ZXMiXSwibmJmIjoxNzYTc2NjY0NjY0NH0.7z9WhiQ7luMkQAXeF40re9N5Cqy84aSmNC3X0B-00EY"
});

API.interceptors.request.use(
  (request: InternalAxiosRequestConfig) => {
    request.headers.Authorization = `Bearer ${cookies?.access_token}`;
    return request;
  },
  (error: AxiosError) => {
    return Promise.reject(error);
  },
);

API.interceptors.response.use(
  (response: AxiosResponse) => {
    return response;
  },
  (error: AxiosError) => {
    return Promise.reject(error);
  },
);

export default API;
